services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.unified
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    depends_on:
      - db
  # backend:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #   command: sh -c "npx prisma migrate deploy && npm run prisma:seed && node index.js"
  # frontend:
  #   build: ./client
  #   ports:
  #     - "5173:80"
  #   depends_on:
  #     - backend
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reportdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: 